# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kde5-oxygen

# >> macros
# << macros

Summary:    KDE's default style and look
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-oxygen.yaml
Source101:  kde5-oxygen-rpmlintrc
Requires:   kde5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5WebKit)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  kf5-umbrella
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kconfigwidgets-devel
BuildRequires:  kf5-kguiaddons-devel
BuildRequires:  kf5-kwidgetsaddons-devel
BuildRequires:  kf5-kservice-devel
BuildRequires:  kf5-kcompletion-devel
BuildRequires:  kf5-frameworkintegration-devel
BuildRequires:  kf5-kwindowsystem-devel
BuildRequires:  kde5-kwin-devel

%description
KDE's default style and look.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%package cursor-themes
Summary:    Oxygen cursor themes
Group:      System/Base
BuildArch:  noarch

%description cursor-themes
A full set of cursor themes.


%package sounds
Summary:    Oxygen sounds
Group:      System/Base
BuildArch:  noarch

%description sounds
A full set of sounds for different desktop events.


%package kwin
Summary:    KWin "Oxygen" decoration
Group:      System/Base
Requires:   %{name} = %{version}-%{release}
Requires:   kde5-kwin

%description kwin
This package contains the "Oxygen" decoration for KWin.


%package style
Summary:    QtWidgets "Oxygen" style
Group:      System/Base
Requires:   %{name} = %{version}-%{release}

%description style
This package contains the "Oxygen" style for QtWidgets.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING
%{_kde5_bindir}/oxygen-demo5
%{_kde5_bindir}/oxygen-settings5
%{_kde5_libdir}/*.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kde5_libdir}/*.so
# >> files devel
# << files devel

%files cursor-themes
%defattr(-,root,root,-)
%{_datadir}/icons/*
# >> files cursor-themes
# << files cursor-themes

%files sounds
%defattr(-,root,root,-)
%{_datadir}/sounds/*
# >> files sounds
# << files sounds

%files kwin
%defattr(-,root,root,-)
%{_kde5_plugindir}/kwin/kdecorations/config/kwin_oxygen_config.so
%{_kde5_plugindir}/kwin/kdecorations/kwin3_oxygen.so
# >> files kwin
# << files kwin

%files style
%defattr(-,root,root,-)
%{_qt5_plugindir}/kstyle_oxygen_config.so
%{_qt5_plugindir}/styles/oxygen.so
%{_kde5_datadir}/kstyle/themes/oxygen.themerc
# >> files style
# << files style
